-- Currencies table for course pricing
CREATE TABLE IF NOT EXISTS Currencies (
    currencyId INT AUTO_INCREMENT PRIMARY KEY,
    currencyCode VARCHAR(3) NOT NULL UNIQUE,
    currencyName VARCHAR(50) NOT NULL,
    currencySymbol VARCHAR(10) NOT NULL,
    isActive TINYINT(1) DEFAULT 1,
    displayOrder INT DEFAULT 0,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Insert common currencies
INSERT INTO Currencies (currencyCode, currencyName, currencySymbol, displayOrder) VALUES
('RWF', 'Rwandan Franc', 'RWF', 1),
('USD', 'US Dollar', '$', 2),
('EUR', 'Euro', '€', 3),
('GBP', 'British Pound', '£', 4),
('CAD', 'Canadian Dollar', 'C$', 5),
('KES', 'Kenyan Shilling', 'KSh', 6),
('UGX', 'Ugandan Shilling', 'USh', 7),
('TZS', 'Tanzanian Shilling', 'TSh', 8),
('ZAR', 'South African Rand', 'R', 9),
('NGN', 'Nigerian Naira', '₦', 10),
('GHS', 'Ghanaian Cedi', '₵', 11),
('ETB', 'Ethiopian Birr', 'Br', 12),
('MAD', 'Moroccan Dirham', 'MAD', 13),
('EGP', 'Egyptian Pound', 'E£', 14),
('TND', 'Tunisian Dinar', 'DT', 15),
('DZD', 'Algerian Dinar', 'DA', 16),
('XOF', 'West African CFA Franc', 'CFA', 17),
('XAF', 'Central African CFA Franc', 'FCFA', 18),
('AUD', 'Australian Dollar', 'A$', 19),
('JPY', 'Japanese Yen', '¥', 20),
('CNY', 'Chinese Yuan', '¥', 21),
('INR', 'Indian Rupee', '₹', 22),
('BRL', 'Brazilian Real', 'R$', 23),
('MXN', 'Mexican Peso', '$', 24),
('CHF', 'Swiss Franc', 'CHF', 25),
('SEK', 'Swedish Krona', 'kr', 26),
('NOK', 'Norwegian Krone', 'kr', 27),
('DKK', 'Danish Krone', 'kr', 28),
('PLN', 'Polish Zloty', 'zł', 29),
('CZK', 'Czech Koruna', 'Kč', 30),
('HUF', 'Hungarian Forint', 'Ft', 31),
('RON', 'Romanian Leu', 'lei', 32),
('BGN', 'Bulgarian Lev', 'лв', 33),
('HRK', 'Croatian Kuna', 'kn', 34),
('RSD', 'Serbian Dinar', 'дин', 35),
('UAH', 'Ukrainian Hryvnia', '₴', 36),
('RUB', 'Russian Ruble', '₽', 37),
('TRY', 'Turkish Lira', '₺', 38),
('ILS', 'Israeli Shekel', '₪', 39),
('AED', 'UAE Dirham', 'د.إ', 40),
('SAR', 'Saudi Riyal', 'ر.س', 41),
('QAR', 'Qatari Riyal', 'ر.ق', 42),
('KWD', 'Kuwaiti Dinar', 'د.ك', 43),
('BHD', 'Bahraini Dinar', 'د.ب', 44),
('OMR', 'Omani Rial', 'ر.ع.', 45),
('JOD', 'Jordanian Dinar', 'د.ا', 46),
('LBP', 'Lebanese Pound', 'ل.ل', 47),
('EGP', 'Egyptian Pound', 'E£', 48),
('ZAR', 'South African Rand', 'R', 49),
('BWP', 'Botswana Pula', 'P', 50),
('ZMW', 'Zambian Kwacha', 'ZK', 51),
('MWK', 'Malawian Kwacha', 'MK', 52),
('SZL', 'Swazi Lilangeni', 'L', 53),
('LSL', 'Lesotho Loti', 'L', 54),
('NAD', 'Namibian Dollar', 'N$', 55),
('AOA', 'Angolan Kwanza', 'Kz', 56),
('MZN', 'Mozambican Metical', 'MT', 57),
('MGA', 'Malagasy Ariary', 'Ar', 58),
('MUR', 'Mauritian Rupee', '₨', 59),
('SCR', 'Seychellois Rupee', '₨', 60),
('KMF', 'Comorian Franc', 'CF', 61),
('DJF', 'Djiboutian Franc', 'Fdj', 62),
('SOS', 'Somali Shilling', 'S', 63),
('ETB', 'Ethiopian Birr', 'Br', 64),
('ERN', 'Eritrean Nakfa', 'Nfk', 65),
('SDG', 'Sudanese Pound', 'ج.س.', 66),
('SSP', 'South Sudanese Pound', '£', 67),
('CDF', 'Congolese Franc', 'FC', 68),
('XAF', 'Central African CFA Franc', 'FCFA', 69),
('XOF', 'West African CFA Franc', 'CFA', 70),
('GMD', 'Gambian Dalasi', 'D', 71),
('GNF', 'Guinean Franc', 'FG', 72),
('SLL', 'Sierra Leonean Leone', 'Le', 73),
('LRD', 'Liberian Dollar', 'L$', 74),
('CVE', 'Cape Verdean Escudo', '$', 75),
('STN', 'São Tomé and Príncipe Dobra', 'Db', 76),
('AOA', 'Angolan Kwanza', 'Kz', 77),
('ZMW', 'Zambian Kwacha', 'ZK', 78),
('BWP', 'Botswana Pula', 'P', 79),
('SZL', 'Swazi Lilangeni', 'L', 80),
('LSL', 'Lesotho Loti', 'L', 81),
('NAD', 'Namibian Dollar', 'N$', 82),
('ZAR', 'South African Rand', 'R', 83),
('MZN', 'Mozambican Metical', 'MT', 84),
('MGA', 'Malagasy Ariary', 'Ar', 85),
('MUR', 'Mauritian Rupee', '₨', 86),
('SCR', 'Seychellois Rupee', '₨', 87),
('KMF', 'Comorian Franc', 'CF', 88),
('DJF', 'Djiboutian Franc', 'Fdj', 89),
('SOS', 'Somali Shilling', 'S', 90),
('ETB', 'Ethiopian Birr', 'Br', 91),
('ERN', 'Eritrean Nakfa', 'Nfk', 92),
('SDG', 'Sudanese Pound', 'ج.س.', 93),
('SSP', 'South Sudanese Pound', '£', 94),
('CDF', 'Congolese Franc', 'FC', 95),
('XAF', 'Central African CFA Franc', 'FCFA', 96),
('XOF', 'West African CFA Franc', 'CFA', 97),
('GMD', 'Gambian Dalasi', 'D', 98),
('GNF', 'Guinean Franc', 'FG', 99),
('SLL', 'Sierra Leonean Leone', 'Le', 100),
('LRD', 'Liberian Dollar', 'L$', 101),
('CVE', 'Cape Verdean Escudo', '$', 102),
('STN', 'São Tomé and Príncipe Dobra', 'Db', 103)
ON DUPLICATE KEY UPDATE 
    currencyName = VALUES(currencyName),
    currencySymbol = VALUES(currencySymbol),
    displayOrder = VALUES(displayOrder),
    updatedAt = CURRENT_TIMESTAMP;
